### ISSUE TITLE
start/end标注方式

### ISSUE THREAD

**Issue by Backlight-SS** [StanleyLsx/entity_extractor_by_pointer#1]
你好，请问一下start/end这种标注方式，相对于传统的CRF有什么优点呢？

**Comment by stanleylsx** [comment]
CRF的话是可以纠正序列先后转移的顺序，但是双指针不会，这个算是它的缺点。

但是双指针抽取实体的办法直接来自于指针网络，一开始用在QA问题中，它抽取实体的时候自然带有它的有点:

1.可以抽取包含或重叠实体。

2.可以抽取比较长的实体，如一段定义。

上述两点在crf中没有办法实现，但是在短实体的抽取上效果可能没有crf好(至少这个仓库中的网络结构)。

其他内容可以参考下苏神关系抽取的文章。
