### ISSUE TITLE
一直是0，不确定错在哪里？

### ISSUE THREAD

**Issue by snakecy** [StanleyLsx/entity_extractor_by_pointer#4]
![image](https://user-images.githubusercontent.com/12490881/126962351-e8d116e2-63e3-45d8-9aad-a41cbb69ed09.png)

**Comment by stanleylsx** [comment]
项目中给的配置错误，已经修改。

**Comment by qiutzh** [comment]
@StanleyLsx 这个问题仍然存在，并没有解决。

**Comment by guo-xiaomeng** [comment]
看看是不是数据标注时候结束位多了一位
