### ISSUE TITLE
验证时出错

### ISSUE THREAD

**Issue by chenjiawei22** [StanleyLsx/entity_extractor_by_pointer#5]
def extract_entities(configs, tokenizer, text, model, device):
    """
    从验证集中预测到相关实体
    """
    predict_results = {}
    encode_results = tokenizer(text, padding='max_length')
    input_ids = encode_results.get('input_ids')
    token = tokenizer.convert_ids_to_tokens(input_ids)
    mapping = rematch(text, token)
    token_ids = torch.unsqueeze(torch.LongTensor(input_ids), 0) .to(device)
    attention_mask = torch.unsqueeze(torch.LongTensor(encode_results.get('attention_mask')), 0).to(device)
    model_outputs = model(token_ids, attention_mask).detach().to('cpu')
    decision_threshold = float(configs.decision_threshold)
    for model_output in model_outputs:
        start = np.where(model_output[:, :, 0] > decision_threshold)
        end = np.where(model_output[:, :, 1] > decision_threshold)
        for _start, predicate1 in zip(*start):
            for _end, predicate2 in zip(*end):
                if _start <= _end and predicate1 == predicate2:
                    if len(mapping[_start]) > 0 and len(mapping[_end]) > 0:
                        start_in_text = mapping[_start][0]
                        end_in_text = mapping[_end][-1]
                        entity_text = text[start_in_text: end_in_text + 1]
                        predict_results.setdefault(predicate1, set()).add(entity_text)
                    break
    return predict_results

to('cpu')
验证时 RuntimeError: CUDA error: device-side assert triggered

**Comment by stanleylsx** [comment]
> def extract_entities(configs, tokenizer, text, model, device): """ 从验证集中预测到相关实体 """ predict_results = {} encode_results = tokenizer(text, padding='max_length') input_ids = encode_results.get('input_ids') token = tokenizer.convert_ids_to_tokens(input_ids) mapping = rematch(text, token) token_ids = torch.unsqueeze(torch.LongTensor(input_ids), 0) .to(device) attention_mask = torch.unsqueeze(torch.LongTensor(encode_results.get('attention_mask')), 0).to(device) model_outputs = model(token_ids, attention_mask).detach().to('cpu') decision_threshold = float(configs.decision_threshold) for model_output in model_outputs: start = np.where(model_output[:, :, 0] > decision_threshold) end = np.where(model_output[:, :, 1] > decision_threshold) for _start, predicate1 in zip(*start): for _end, predicate2 in zip(*end): if _start <= _end and predicate1 == predicate2: if len(mapping[_start]) > 0 and len(mapping[_end]) > 0: start_in_text = mapping[_start][0] end_in_text = mapping[_end][-1] entity_text = text[start_in_text: end_in_text + 1] predict_results.setdefault(predicate1, set()).add(entity_text) break return predict_results
> 
> to('cpu') 验证时 RuntimeError: CUDA error: device-side assert triggered

请验证GPU问题
